apiVersion: v1
kind: ConfigMap
metadata:
  name: flow-range
data:
  yaml:
    {{- .Values.data | toYaml | nindent 2}}

  range:
    {{- range .Values.data }}
    - {{ . }}
    {{- end }}

  range-quote:
    {{- range .Values.data }}
    - {{ . | quote }}
    {{- end }}

  range-upper-quote:
    {{- range .Values.data }}
    - {{ . | upper | quote }}
    {{- end }}