apiVersion: v1
kind: Pod
metadata:
  name: pod-preferred
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - {key: ch, operator: Exists}
  containers:
    - name: container
      image: hyun6ik/hello
  terminationGracePeriodSeconds: 0