apiVersion: v1
kind: Pod
metadata:
  name: liveness-exam
spec:
  containers:
    - name: busybox-container
      image: busy/box
      args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
      livenessProbe:
        exec:
          command:
            - ls
            - /tmp/healthy
        failureThreshold: 2
        periodSeconds: 5
        successThreshold: 1
        timeoutSeconds: 1
        initialDelaySeconds: 10