apiVersion: v1
kind: Pod
metadata:
  name: pod-pause
spec:
  nodeSelector:
    kubernetes.io/hostname: hyun6ik--k8s-node1.example.com
  containers:
    - name: container1
      image: kubetm/p8000
      ports:
        - containerPort: 8000
    - name: container2
      image: kubetm/p8080
      ports:
        - containerPort: 8080