apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-mainui
  annotations:
    kubernetes.io/change-cause: version 2.4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      name: main-pod
      labels:
        name: apache
        app: main
        rel: stable
    spec:
      containers:
        - name: httpd
          image: httpd:2.4
          ports:
          - containerPort: 80