apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: bluegreen
spec:
  replicas: 2
  selector:
    matchLabels:
      ver: v1
  template:
    metadata:
      name: bg-pod
      labels:
        ver: v1
    spec:
      containers:
        - name: container
          image: tmkube/app:v1
      terminationGracePeriodSeconds: 0