apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-1
spec:
  replicas: 2
  selector:
    matchLabels:
      type: app
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  template:
    metadata:
      name: dp-pod
      labels:
        type: app
    spec:
      containers:
        - name: container
          image: nginx:1.14
      terminationGracePeriodSeconds: 0