apiVersion: v1
kind: Pod
metadata:
  name: pod-9
spec:
  containers:
    - name: container
      image: hyun6ik/hello
      resources:
        requests:
          memory: 1Gi
        limits:
          memory: 3Gi