apiVersion: v1
kind: Pod
metadata:
  name: pod-1
spec:
  containers:
    - name: containter1
      image: hyun6ik/hello
      ports:
        - containerPort: 8000
    - name: container2
      image: nginx:1.14
      ports:
        - containerPort: 8080