apiVersion: v1
kind: ReplicationController
metadata:
  name: replication-1
spec:
  replicas: 2
  selector:
    app: rc
  template:
    metadata:
      name: pod-1
      labels:
        app: rc
    spec:
      containers:
        - name: container
          image: hyun6ik/hello