apiVersion: v1
kind: Pod
metadata:
  name: crd-pod
  annotations:
    helm.sh/hooks: pre-upgrade
spec:
  restartPolicy: Never
  containers:
    - name: container
      image: kubetm/app
      command: [ "sh", "-c", "echo 'start'; sleep 10; echo 'done'" ]
