apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      type: app
  replicas: 1
  template:
    metadata:
      labels:
        type: app
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      initContainers:
        - name: init-myservice
          image: kubetm/app
          command: ["sh", "-c", "echo 'start'; sleep 10; echo 'done'"]
      containers:
        - name: container
          image: kubetm/app

---
apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  selector:
    type: app
  ports:
    - port: 80
      targetPort: 8080