apiVersion: v1
kind: Pod
metadata:
  name: pod-volume-4
spec:
  containers:
    - name: container
      image: hyun6ik/hello
      volumeMounts:
        - name: pvc-pv
          mountPath: /mount3
  volumes:
    - name: pvc-pv
      persistentVolumeClaim:
        claimName: pvc-1