apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      type: app
  replicas: 1
  template:
    metadata:
      labels:
        type: app
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configMap.yaml") . | sha256sum }}
        #        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      initContainers:
        - name: init-myservice
          image: kubetm/app
          command: ["sh", "-c", "echo 'start'; sleep 30; echo 'done'"]
      containers:
        - name: container
          image: kubetm/app
          envFrom:
            - configMapRef:
                name: test-cm
          volumeMounts:
            - name: volume
              mountPath: /hostPath
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: test-pvc