apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
  labels:
    name: test-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1G
  hostPath:
    path: /host1
    type: DirectoryOrCreate