apiVersion: apps/v1
kind: Deployment
metadata:
  name: mainui-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mainui
      rel: canary
  template:
    metadata:
      labels:
        app: mainui
        rel: canary
    spec:
      containers:
        - name: mainui-container
          image: nginx:1.15
          ports:
            - containerPort: 80