apiVersion: v1
kind: Pod
metadata:
  name: pod-mount
spec:
  containers:
    - name: container
      image: hyun6ik/hello
      volumeMounts:
        - name: file-volume
          mountPath: /mount1
  volumes:
    - name: file-volume
      configMap:
        name: cm-file