apiVersion: v1
kind: Pod
metadata:
  name: pre-pod3
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "1"
spec:
  containers:
    - name: container
      image: kubetm/init
      command: ["sh", "-c", "echo 'start'; sleep 10; echo 'done'"]