apiVersion: v1
kind: Pod
metadata:
  name: annotation-pod
  annotations:
    builder: "aaa@bbb@ccc"
    buildDate: "20220109"
    imageregistry: "https://hub.docker.com/"
spec:
  containers:
    - name: nginx
      image: nginx:1.14
      ports:
        - containerPort: 80