apiVersion: apps/v1
kind: Deployment
metadata:
  name: mainui-stable
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mainui
      rel: stable
  template:
    metadata:
      labels:
        app: mainui
        rel: stable
    spec:
      containers:
        - name: mainui-container
          image: nginx:1.14
          ports:
            - containerPort: 80
