apiVersion: v1
kind: Pod
metadata:
  name: web1
  labels:
    type: web1
spec:
  nodeSelector:
    a-team: "1"
  containers:
    - name: container
      image: hyun6ik/hello
  terminationGracePeriodSeconds: 0