apiVersion: v1
kind: Pod
metadata:
  name: server2
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: a-team
          labelSelector:
            matchExpressions:
              - {key: type, operator: In, values: [web2]}
  containers:
    - name: container
      image: hyun6ik/hello
  terminationGracePeriodSeconds: 0