apiVersion: v1
kind: Pod
metadata:
  name: pod-1
spec:
  containers:
    - name: container
      image: hyun6ik/hello
      resources:
        requests:
          memory: 0.5Gi
        limits:
          memory: 0.5Gi