apiVersion: v1
kind: Pod
metadata:
 name: pod-2
spec:
  containers:
    - name: container
      image: hyun6ik/hello
      resources:
        requests:
          memory: 0.6Gi
        limits:
          memory: 0.6Gi