apiVersion: v1
kind: Service
metadata:
  name: service-2
spec:
  type: NodePort
  selector:
    app: pod
  ports:
    - port: 9000
      targetPort: 8000
      nodePort: 30000
#  externalTrafficPolicy: Local