apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    app: pod
spec:
  nodeSelector:
    kubernetes.io/hostname: hyun6ik-k8s-node2.example.com
  containers:
    - name: container
      image: hyun6ik/hello
      ports:
        - containerPort: 8000